
# Site wide configuration

# url: https://monkey-sheng.github.io
title: Jason Hu's personal website
locale: en_US
logo: #35x45.jpeg # displayed on top banner # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Jason (Jiasheng) Hu
  avatar: 35x45.jpeg  # will be displayed next to name
  bio: 2nd Year PhD student at the University of Toronto, supervised by Prof. Qizhen Zhang; BEng Hon. @ University of Edinburgh.
  website: #https://library.rochester.edu
  email: jasonhu@cs.toronto.edu # email
  twitter: #RCLibraries
  linkedin: #linkedin id
  github: monkey-sheng
  orcid: #orcid id
  researchgate: #researchgate username 
  mendeley: #mendeley username 
  google:
    plus: #username
    analytics:
    verify:
    scholar: #google scholar 'user' id 
  facebook: #rivercampuslibraries
  instagram: #rclibraries
  bing-verify:
  stackoverflow: #123456/username from a "https://stackoverflow.com/users/123456/username" link
  xing: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #RCLibraries
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  disqus-shortname: #username
  resume: /assets/static/CV-Jiasheng(Jason)Hu.pdf #https://monkey-sheng.github.io/CV-Jiasheng(Jason)Hu.pdf #url to your CV

# The following adjust the accents for your site. If you would like to further edit colors, fonts, font sizes, etc.
# you may do so in _sass/variables.scss
highlight-color: '#222222' #UR gold
lowlight-color: '#073661' #UR navy

  # NOTE: If you would like your site to be licensed under a creative commons license, uncomment the 'yes' next to the type of license you wish to use.
creative-commons:
  cc-by: #yes
  cc-by-nc: #yes

#DO NOT EDIT BEYOND THIS POINT
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
